<img src= "./resources/title.png">

### Contents:

1. Why Linear Algebra?
2. Data Types for Linear Algebra
3. Operations on Vectors and Matrices
    - Addition and Subtraction
    - Broadcasting
    - Multiplication (3 kinds)
    - Division
    

# Part 1. Why Linear Algebra?

Linear Algebra is the basis of many machine learning models.

Data is usually already set up into a matrix by default!

<img src= "./resources/dataset.jpeg">

It can be used to model complicated things like language

<img src = "./resources/Word-Vectors.png">

Important for image compression and recognition

<img src = "./resources/images.gif">

Recommendation engines are able to make much more sophisticated recommendations by using linear algebra in conjunction with user and content data.

<img src = "./resources/netflix.png">





<img src="./resources/linalgmeme.png" alt="drawing" width="400"/>

# Part 2: Data Types for Linear Algebra

<img src = "./resources/datadogs.jpg">

* Scalars only have magnitude.

* A vector is an array with **magnitude and direction**. The coordinates of a vector represent where the tip of the vector would be if you travelled from the origin, and the magnitude of a vector would be its length in space.

* Matrices can be interpreted differently in different contexts but it's often used to represent multiple simultaneous vectors. 

* A vector or matrix can be multiplied by a scalar to create a change in **scale** and/or direction.

* Tensors are made up of matrices with the same dimensions.

Vectors, matrices and tensors are represented by NumPy arrays. **Not lists!!!** We can use `np.array.shape` to explore the dimensions of these data structures.


In [1]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5, 6])
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[1, 2], [3, 4], [5, 6]])
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(vector)
print('vector shape:', vector.shape, '\n')
print(matrix1)
print('matrix1 shape:', matrix1.shape, '\n')
print(matrix2)
print('matrix2 shape:', matrix2.shape, '\n')
print(tensor)
print('tensor shape:', tensor.shape, '\n')

[1 2 3 4 5 6]
vector shape: (6,) 

[[1 2 3]
 [4 5 6]]
matrix1 shape: (2, 3) 

[[1 2]
 [3 4]
 [5 6]]
matrix2 shape: (3, 2) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
tensor shape: (2, 2, 2) 



In [2]:
# mess around with indexing a tensor

tensor[0]

array([[1, 2],
       [3, 4]])

### Magnitude of a vector

$length = \|v \| = \sqrt{v \cdot v} = (v_{1}^2 + v_{2}^2 + \cdot \cdot \cdot \cdot + v_{n}^2)$


In [3]:
np.linalg.norm(vector)

9.539392014169456

### Transposing

Calling `.transpose()` on an array **reverses** its shape order.

In [4]:
print(matrix1)
print('matrix1 shape:', matrix1.shape, '\n')

# transposed
print(matrix1.transpose(), '\n')
print('matrix1.transpose() shape:', matrix1.transpose().shape)

[[1 2 3]
 [4 5 6]]
matrix1 shape: (2, 3) 

[[1 4]
 [2 5]
 [3 6]] 

matrix1.transpose() shape: (3, 2)


In [7]:
tensor2 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], 
           [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])

print(tensor2, '\n')
print('shape of tensor2: ', tensor2.shape, '\n')

# transposed
print(tensor2.transpose(0,2,1), '\n')
print('shape of tensor2.transpose(): ', tensor2.transpose(0,2,1).shape)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]] 

shape of tensor2:  (2, 4, 3) 

[[[ 1  4  7 10]
  [ 2  5  8 11]
  [ 3  6  9 12]]

 [[13 16 19 22]
  [14 17 20 23]
  [15 18 21 24]]] 

shape of tensor2.transpose():  (2, 3, 4)


# Part 3: Operations on Vectors and Matrices

## a. Addition & Subtraction

For addition and subtraction of vectors, matrices and even tensors, as long as the dimensions are equal the operation occurs **element-wise**. This means given two vectors `v` and `w`:

$ \vec{v} = \begin{bmatrix}v_{1} \\v_{2}\end{bmatrix} $


$ \vec{w} = \begin{bmatrix}w_{1} \\w_{2}\end{bmatrix} $

$ \vec{v} + \vec{w} = \begin{bmatrix}v_{1} + w_{1} \\v_{2} + w_{2}\end{bmatrix} $

In [9]:
# numerical example 

v = np.array([2, 4])
w = np.array([3, 2])
v - w # what about v-w?
# what does this look like graphically?

array([-1,  2])

## b. Broadcasting

NumPy arrays allow for something known as **broadcasting**, which happens when you perform operations across arrays with different number of dimensions. NumPy makes duplicates of the lower-dimension array **as long as the higher-dimension array *contains* the same shape** in order to execute the operation. Order of the `.shape` tuple matters!

In [10]:
scalar = 4
print(vector)

print(vector + scalar)

[1 2 3 4 5 6]
[ 5  6  7  8  9 10]


In [11]:
v1 = np.array([1, 0, 1])
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m1 - v1

array([[0, 2, 2],
       [3, 5, 5]])

What shapes of matrices and vectors can be broadcast onto `tensor2`?

In [12]:
print(tensor2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


In [13]:
# notes here: 
# scalar
# vector 3 long
# matrix 4x3

## c. Multiplication

### i. Hadamard Product

Hadamard Multiplication occurs element-wise, and therefore can only occur between matrices of the same shape **OR** when broadcasting can occur. The Hadamard product is very easy in NumPy: just use `*`!


\begin{equation}
\begin{bmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{bmatrix}
\circ
\begin{bmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2}
\end{bmatrix}
=
\begin{bmatrix}
a_{1,1}\times b_{1,1} & a_{1,2}\times b_{1,2} \\
a_{2,1}\times b_{2,1} & a_{2,2}\times b_{2,2}
\end{bmatrix}
\end{equation}


In [15]:
# Use NumPy to calculate the Hadamard product of
# [[1, 2], [1, 2]] and [[3, 4], [5, 9]]

# Your code here:
a = np.array([[1,2], [1,2]])
b = np.array([[3,4], [5,9]])
a * b

array([[ 3,  8],
       [ 5, 18]])

### ii. Dot Product

Dot product is probably the most relevant kind of multiplication for our use cases. The dot product of matrices is also commonly known as **Matrix Multiplication**. Unless otherwise stated, _multiplication_ refers to this kind of multiplication.


\begin{equation}
\begin{bmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{bmatrix}
\times
\begin{bmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2}
\end{bmatrix}
=
\begin{bmatrix}
a_{1,1}\times b_{1,1} + a_{1,2}\times b_{2,1} & a_{1,1}\times b_{1,2} + a_{1,2}\times b_{2,2} \\
a_{2,1}\times b_{1,1} + a_{2,2}\times b_{2,1} & a_{2,1}\times b_{1,2} + a_{2,2}\times b_{2,2}
\end{bmatrix}
\end{equation}


We take the **rows** (horizontal) of the first matrix and do an element-wise product with the **columns** (vertical) of the second matrix. With this rule, what are the shape restrictions to doing matrix multiplication?

i.e. if we want to multiply matrices $A$ and $B$ where the dimensions of $A$ and $B$ are $m \times n$ and $p \times q$ respectively.

In [ ]:
# notes here!
# 
# 
# 

Using NumPy arrays, dot-multiply the matrices
\begin{bmatrix}
3 & 2 \\
5 & 7
\end{bmatrix}
\begin{bmatrix}
2 & 4 \\
3 & 10
\end{bmatrix}

in the code-cell below using `np.dot()`. Look up the documentation! Remember that you need square brackets around the whole array!

In [18]:
# Your code here: 
c = np.array([[3,2], [5,7]])
d = np.array([[2,4], [3, 10]])
c.dot(d)

array([[12, 32],
       [31, 90]])

Furthermore, $AB ≠ BA $  and $(AB)C ≠ A(BC)$.

### iii. Cross Product

The cross product is used for more abstract applications of linear algebra and here we'll just define it for vectors.

The result of the cross product of two vectors: $A \times B = |A||B|sin( \theta) n $
- ($n$ is the unit vector perpendicular to the plane formed by the two vectors)
- has a magnitude (length) equal to the area of the parallelogram formed by the two vectors
- perpendicular to the plane formed by the two vectors
- when you do a cross product, you lose a dimension


## d. Division

just kidding.

### Inverses and the Identity Matrix

It is **not** possible to divide by matrices (broadcasting still works element-wise). What we can do is find the **inverse** of a matrix. When a matrix is multiplied by its inverse, it results in the identity matrix. 

<img src = "./resources/inverse.webp">

The order of multiplication does not matter for a matrix and its inverse:

$A \cdot A^{-1} = A^{-1} \cdot A $

An identity matrix is a square with a diagonal of 1's moving from left to right and the remaining numbers 0. When a matrix is multiplied by an identity matrix, it will result in the same matrix (think of it as the operational equivalent to 1 for linear algebra).

<img src = "./resources/identity_matrix.svg">



In [19]:
# showing the effect of multiplying by the identity matrix

x = np.array([[4,8,10],[3,9,12],[5,10,15]])
i_3 = np.identity(3)

print(x, '\n')
print(i_3, '\n')
print(x.dot(i_3))

[[ 4  8 10]
 [ 3  9 12]
 [ 5 10 15]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[ 4.  8. 10.]
 [ 3.  9. 12.]
 [ 5. 10. 15.]]


In [20]:
# inverse of x and multiplying by x

inv_x = np.linalg.inv(x)
print(inv_x, '\n')

print(np.round(x.dot(inv_x)))

[[ 5.00000000e-01 -6.66666667e-01  2.00000000e-01]
 [ 5.00000000e-01  3.33333333e-01 -6.00000000e-01]
 [-5.00000000e-01 -7.40148683e-17  4.00000000e-01]] 

[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]


### Additional Resources
* 3 Blue 1 Brown:  https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_a
* Matrix approach to Linear Regression: http://www.stat.columbia.edu/~fwood/Teaching/w4315/Fall2009/lecture_11
* [link to fun desmos interaction](https://www.desmos.com/calculator/yovo2ro9me)
* [Link to good video on scalars and vectors](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)
* [What is X^T * X?](https://stats.stackexchange.com/questions/267948/intuitive-explanation-of-the-xtx-1-term-in-the-variance-of-least-square/267963)